name: omar_ahmad_advanced_concept
description: "A new Flutter project."
publish_to: "none"
version: 1.0.2+1

environment:
  sdk: ^3.5.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # State managment
  # https://pub.dev/packages/flutter_bloc/install
  flutter_bloc: ^9.0.0
  # Code generater (mainly used with cubit & retrifit)
  # https://pub.dev/packages/freezed/install
  freezed: ^2.5.7
  # Annotations for the freezed code-generator. This package does nothing without freezed too.
  # https://pub.dev/packages/freezed_annotation/install
  freezed_annotation: ^2.4.4
  # For Dependency injection
  # https://pub.dev/packages/get_it/install
  get_it: ^8.0.2
  # Automatically generate code for converting to and from JSON by annotating Dart classes.
  # https://pub.dev/packages/json_serializable/install
  json_serializable: ^6.9.0
  # https://pub.dev/packages/json_annotation/install
  json_annotation: ^4.9.0
  # Networking
  # https://pub.dev/packages/dio/install
  dio: ^5.7.0
  # A Dio Client Generator
  # https://pub.dev/packages/retrofit/install
  retrofit: ^4.4.1
  # Retrofit generator
  # https://pub.dev/packages/retrofit_generator/install
  retrofit_generator: ^9.1.5
  # https://pub.dev/packages/pretty_dio_logger/install
  pretty_dio_logger: ^1.4.0
  # Localization
  # https://pub.dev/packages/intl/install
  intl: ^0.19.0
  # https://pub.dev/packages/easy_localization/install
  easy_localization: ^3.0.7
  # Splash Screen
  # https://pub.dev/packages/flutter_native_splash/install
  flutter_native_splash: ^2.4.3
  # An SVG rendering and widget library for Flutter, which allows painting
  # https://pub.dev/packages/flutter_svg/install
  flutter_svg: ^2.0.15
  # For Adapting screen and Font size
  # https://pub.dev/packages/flutter_screenutil/install
  flutter_screenutil: ^5.9.3
  # Custom dropdown widget allows to add highly customizable dropdown widget in project
  # https://pub.dev/packages/animated_custom_dropdown/install
  animated_custom_dropdown: ^3.1.1
  # Collection of cool and beautiful text animations
  # https://pub.dev/packages/animated_text_kit/install
  animated_text_kit: ^4.2.2
  # For fireBase distribution and firebase services
  # https://pub.dev/packages/firebase_core/install
  firebase_core: ^3.9.0
  # A package provides an easy way to add shimmer effect
  # https://pub.dev/packages/shimmer/install
  shimmer: ^3.0.0
  # Reading and writing simple key-value pairs
  # https://pub.dev/packages/shared_preferences/install
  shared_preferences: ^2.3.5
  # Provides API to store data in secure storage
  # https://pub.dev/packages/flutter_secure_storage/install
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  # https://pub.dev/packages/build_runner/install
  build_runner: ^2.4.13
  # https://pub.dev/packages/flutter_gen_runner/install
  flutter_gen_runner: ^5.8.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter_gen:
  output: lib/core/assets_gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)

  # Optional
  integrations:
    flutter_svg: true
    flare_flutter: true
    rive: true
    lottie: true

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/svgs/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
