# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Andorid Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --flavor Production -t lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
        app: "1:1013887525406:android:3d9cb2c872ade991e1c40f",
        firebase_cli_token: "1//03Q1UM9V8LdLqCgYIARAAGAMSNwF-L9IrOo36rx98vfZRTrRVdpC2AshfMhxe_qpGHe9aQj7mVVHJBRavky0pyhkcVdjMdFogdVY",
        # android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
        testers: "wael.alash04@gmail.com",
        release_notes: "First Fastlane Firebase Distribution"
  ) 
  end
end
